### ISSUE TITLE
minClaimPrice improves

### ISSUE THREAD

**Issue by artman325** [Intercoin/TradedTokenContract#63]
Remake the static minClaimPrice into a dynamic function, such as function(x), which will depend on the reserveToken balance on the Uniswap Pair, time, or any other factor

for example
`g(t) = t * 5`
`f(x,t) = x * x / 1000 / 1000 - g(t)` 

**MainGoal:**  no one has too many tokens
**Goal** And Price will grow with time or with totalReserves(USDT in pool)
it's only for `claim` and `availableToClaim`

**[update 12.05]**
forget the previous. now we need to do the following:
Make Emission struct that setup when init
```
struct Emission
{
    uint128 amount; // of tokens
    uint32 frequency; // in seconds
    uint32 period; // in seconds
    uint32 decrease; // out of FRACTION 10,000
    int32 priceGainMinimum; // out of FRACTION 10,000
}
```
also Remove the current availableToClaim checks in TradedToken except for the check for minimum price, which owner can raise, and now just check the following:
```
10000 * (currentPrice - lastPrice) / lastPrice < priceGainMinimum
```
where `currentPrice  `and `lastPrice `are cumulativeprice from uniswapv2 and updated only in added `claim` and `addinitialliquidity`
So since cumulativeprice will change only after swap(or changed liquidity) and we will save it aftrer claiming, it will be available to claim only once. Then, We need to wait when some swap or add liquidity

**Comment by artman325** [comment]
The current functionality allows adjusting the `minClaimPrice`, thereby reducing the number of tokens that can be claimed. The owner can call [`restrictClaiming`](https://github.com/Intercoin/TradedTokenContract/blob/cdfbce7e1a8fa9e8e09684019f06718efd2a5d0f/contracts/TradedToken.sol#L508-L531)and specify `newMinimumClaimPrice` once `MIN_CLAIM_PRICE_UPDATED_TIME` has passed.

I think it will be enough and solve this issue

**Comment by EGreg** [comment]
No, not enough. For one thing, because owner can simply renounce ownership.

We need to set a real curve for the minimumClaimPrice, and remove the other stuff we had.

Simply, availableToClaim should be obtained from current price, and minimumPrice for the current conditions. The minimumPrice would be obtained from some formula involving the time elapsed since some startTime (e.g. liquidity pool was deployed) and maybe amount of reserveToken in hat pool. Play around with the possible functions. Maybe we'll just make it time-based.

**Comment by EGreg** [comment]
availableToClaim is derived from ... if all tokens ever claimed were sold, what would the current price drop to?

the problem is that some of the tokens claimed may have *already* been sold in the pool, dropping the price, but they would be counted anyway ... unless we track when claimed tokens were sold in the pool, which is too much work and storage. Hmm.
